apiVersion: v1
kind: Pod
metadata:
  name: pets-v1
spec:
  containers:
  - name: my-pod
    image: alpine:3.7
    command: 
      - /bin/sh
      - -c
      - echo "cat=$(CAT_NAME) and dog=$(DOG_NAME)"
    env:
    - name: CAT_NAME
      valueFrom:
        configMapKeyRef:
          name: pets
          key: cat
    - name: DOG_NAME
      valueFrom:
        configMapKeyRef:
          name: pets 
          key: dog
  restartPolicy: Never
